env:
  browser: true
  es2021: true
  node: true

extends:
  - react-app
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended

parserOptions:
  ecmaVersion: 12
  sourceType: module

plugins:
  - react
  - jsx-a11y

rules:
  react/prop-types: off
  jsx-a11y/anchor-is-valid: off
